services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgresrd
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: filedownloadrd
    ports:
      - "5443:5432"
    volumes:
      - fdpgdata:/var/lib/postgresql/data
volumes:
  fdpgdata: